model_name: "meta-llama/Meta-Llama-3.1-8B"
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
target_modules:
  - "q_proj"
  - "v_proj"
  - "k_proj"
  - "o_proj"
  - "gate_proj"
  - "up_proj"
  - "down_proj"
bias: "none"
task_type: "CAUSAL_LM"
